-- CREATE SCHEMA student
CREATE SCHEMA student;

-- CREAT TABLE STUDENT.INFO
CREATE TABLE STUDENT.STUDENT
(
	ID INT IDENTITY(1,1) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	AGE INT NOT NULL,
	STANDARD VARCHAR(5) NOT NULL,
	SECTION VARCHAR(5) NOT NULL,
	CONSTRAINT PK_INFO PRIMARY KEY (ID)
)